# ENVIRONMENT OPTIONS
DOCUMENT_NAME	= main
DOCUMENT_PATH	= .
BUILD_PATH		= ./build
OUTPUT_PATH		= .
OUTPUT_NAME		= minhas-anotacoes
WEBSITE_PATH	= ../pages/giordanorn.github.io

# COMPILING OPTIONS
COMPILER		= pdflatex
COMPILER_FLAGS	= -halt-on-error -output-directory $(BUILD_PATH)
BIBER			= biber
BIBER_FLAGS		= --input-directory $(BUILD_PATH) --output-directory $(BUILD_PATH)

# ALIASES
BUILD_FILES		= $(BUILD_PATH)/$(DOCUMENT_NAME).{log,aux,bcf,out,run.xml,toc}
BIB_FILES		= $(BUILD_PATH)/$(DOCUMENT_NAME).{bbl,blg}

.PHONY: default help build clean cleanall

default: help

help:
	@echo "These are all the options available:"
	@echo -e "build\t\t- compile the .tex files to generate the pdf"
	@echo -e "clean\t\t- remove all the files generated by the 'build' option."
	@echo -e "cleanall\t\t- remove all the files generated by the 'build' option, including the pdf file."
	@echo -e "help\t\t- show this message."
	
build: cleanall
	$(COMPILER) $(COMPILER_FLAGS) $(DOCUMENT_PATH)/$(DOCUMENT_NAME).tex \
	&& $(BIBER) $(BIBER_FLAGS) $(DOCUMENT_NAME) \
	&& $(COMPILER) $(COMPILER_FLAGS) $(DOCUMENT_PATH)/$(DOCUMENT_NAME).tex \
	&& $(COMPILER) $(COMPILER_FLAGS) $(DOCUMENT_PATH)/$(DOCUMENT_NAME).tex \
	&& mv $(BUILD_PATH)/$(DOCUMENT_NAME).pdf $(OUTPUT_PATH)

clean:
	rm -f $(BUILD_FILES)
	rm -f $(BIB_FILES)

cleanall: clean
	rm -f $(OUTPUT_PATH)/$(DOCUMENT_NAME).pdf

deploy:
	cp $(OUTPUT_PATH)/$(DOCUMENT_NAME).pdf $(WEBSITE_PATH)/$(OUTPUT_NAME).pdf